# Pre-commit hooks configuration
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]
        require_serial: true
      
      - id: ruff
        name: ruff
        entry: python -m ruff check
        language: system
        types: [python]
        require_serial: true
      
      - id: mypy
        name: mypy
        entry: python -m mypy
        language: system
        types: [python]
        pass_filenames: false
        args: [src/merge_segments]
        require_serial: true
      
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
        stages: [pre-push]
